import 'server-only';

import { and, asc, eq } from 'drizzle-orm';

import { NotFoundError } from '@/lib/api/errors';
import { decryptSecret } from '@/lib/crypto/secrets';
import { db } from '@/lib/db';
import {
  cliTools,
  sandboxCliInstalls,
  userApiKeys,
  type Sandbox,
  type User,
} from '@/lib/db/schema';
import { ID_PREFIX, newId } from '@/lib/ids';
import { rehydrateProvider } from '@/lib/sandbox/service';

/**
 * Installable CLI coding agents ("terminals by license").
 *
 * The catalogue lives in `cli_tools`, seeded from the vendor-documented install
 * commands and editable by platform admins. Nothing here redistributes a tool:
 * installs run the vendor's own installer inside the user's sandbox, and the
 * only secret Karo ever touches is the user's own BYOK key, decrypted server
 * side, written into a `0600` launcher script inside the sandbox, and never
 * returned to a browser.
 */

export type CliTool = typeof cliTools.$inferSelect;
export type CliInstall = typeof sandboxCliInstalls.$inferSelect;

/** Where the launcher script for a tool lives inside the sandbox. */
export function cliScriptPath(slug: string): string {
  return `/workspace/.karo/cli/${slug}.sh`;
}

export async function listEnabledCliTools(): Promise<CliTool[]> {
  return db
    .select()
    .from(cliTools)
    .where(eq(cliTools.isEnabled, true))
    .orderBy(asc(cliTools.sortOrder), asc(cliTools.name));
}

export async function getCliToolBySlug(slug: string): Promise<CliTool> {
  const rows = await db.select().from(cliTools).where(eq(cliTools.slug, slug)).limit(1);
  const tool = rows[0];
  if (!tool) {
    throw new NotFoundError('CLI tool not found.', {
      title: 'Unknown CLI tool',
      description: 'This tool is not in the catalogue. Ask a platform admin to add it.',
    });
  }
  return tool;
}

export async function latestInstallFor(
  sandboxId: string,
  toolId: string,
): Promise<CliInstall | null> {
  const rows = await db
    .select()
    .from(sandboxCliInstalls)
    .where(
      and(eq(sandboxCliInstalls.sandboxId, sandboxId), eq(sandboxCliInstalls.toolId, toolId)),
    )
    .limit(1);
  return rows[0] ?? null;
}

/**
 * Probes the sandbox for the tool's binary and records the result.
 *
 * Uses the same one-shot exec path a user typing `command -v claude` would use,
 * so every provider (Docker, Daytona, BYOS, the simulator) answers honestly.
 */
export async function probeCliInstall(
  sandbox: Sandbox,
  tool: CliTool,
  user: User,
): Promise<{ status: 'installed' | 'missing' | 'unknown'; version: string | null }> {
  const provider = rehydrateProvider(sandbox);
  const result = await provider.execute(sandbox.id, {
    command: `command -v ${tool.binName} && ${tool.binName} ${tool.versionArg}`,
    shell: 'bash',
    cwd: '/workspace',
    timeoutSeconds: 30,
  });

  let status: 'installed' | 'missing' | 'unknown';
  let version: string | null = null;

  if (result.exitCode === 0) {
    status = 'installed';
    // Last non-empty line of `bin --version`; empty (bare `command -v` hit) → null.
    const lines = result.stdout
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean);
    version = lines[lines.length - 1] ?? null;
  } else if (result.exitCode === 1) {
    status = 'missing';
  } else {
    status = 'unknown';
  }

  const now = new Date();
  await db
    .insert(sandboxCliInstalls)
    .values({
      id: newId(ID_PREFIX.cliInstall),
      sandboxId: sandbox.id,
      toolId: tool.id,
      checkedById: user.id,
      status,
      version,
      lastCheckedAt: now,
    })
    .onConflictDoUpdate({
      target: [sandboxCliInstalls.sandboxId, sandboxCliInstalls.toolId],
      set: { status, version, lastCheckedAt: now, checkedById: user.id, updatedAt: now },
    });

  return { status, version };
}

/**
 * The launcher script a sandbox launch writes into the workspace.
 *
 * When the tool authenticates with an API key and the user attaches one from
 * their vault, the key is decrypted here (server side), embedded into a
 * `0600` shell script, and uploaded. It never appears in a command line,
 * terminal history, or an API response.
 */
export function buildLaunchScript(tool: CliTool, apiKey: string | null): string {
  const lines = ['#!/bin/bash', '# Generated by Karo — launch the installed CLI agent.'];
  if (apiKey && tool.apiKeyEnvVar) {
    lines.push(`export ${tool.apiKeyEnvVar}="${escapeShellDoubleQuote(apiKey)}"`);
  }
  lines.push(`exec ${tool.launchCommand || tool.binName} "$@"`);
  return `${lines.join('\n')}\n`;
}

function escapeShellDoubleQuote(value: string): string {
  return value.replace(/([\\"$`])/g, '\\$1');
}

/**
 * Resolves the user's active BYOK key for the tool's provider, if they asked
 * for it to be attached and actually has one. Returns null when not applicable.
 */
export async function resolveVaultKey(
  tool: CliTool,
  user: User,
  attach: boolean,
): Promise<string | null> {
  if (!attach || tool.authKind !== 'api_key' || !tool.apiKeyProviderKey) return null;

  const rows = await db
    .select()
    .from(userApiKeys)
    .where(
      and(
        eq(userApiKeys.userId, user.id),
        eq(userApiKeys.providerKey, tool.apiKeyProviderKey),
        eq(userApiKeys.isActive, true),
      ),
    )
    .limit(1);

  const row = rows[0];
  if (!row) return null;
  return decryptSecret(row.keyCiphertext);
}
